
export const dataManagerConst = {
    UPDATE_COMPONENT_LIST: 'UPDATE_COMPONENT_LIST',
    UPDATE_ALL_SCREEN_FLAG: 'UPDATE_ALL_SCREEN_FLAG',
    UPDATE_MANAGE_COMPONENT_SCREEN_FLAG: 'UPDATE_MANAGE_COMPONENT_SCREEN_FLAG',
    UPDATE_TABLE_LIST: 'UPDATE_TABLE_LIST',
    UPDATE_COMPONENT_PARAM_DEF: 'UPDATE_COMPONENT_PARAM_DEF',
    UPDATE_COMPONENT_DEF_DETAILS: 'UPDATE_COMPONENT_DEF_DETAILS',
    UPDATE_PRV_COMPONENT_DEF_DETAILS: 'UPDATE_PRV_COMPONENT_DEF_DETAILS',
    UPDATE_FIELD_DATA: 'UPDATE_FIELD_DATA',
}
